version: '3.1'
services:
  tomcat:
    image: tomcat
    container_name: tomcat
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./webapps:/usr/local/tomcat/webapps"
    ports:
      - "8080:8080"
