version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:2.401.1-lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    user: root                        #使用root用户启动jenkins
    environment:
      JAVA_OPTS: '-Xms1024M -Xmx2048M -Duser.timezone=Asia/Shanghai'
    volumes:
      - ./data:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock     # 在jenkins的容器内使用docker命令
      #- /usr/bin/docker:/usr/bin/docker               # 这是为了我们可以在jenkins的容器内使用docker命令
    ports:
      - 8080:8080