version: '3'
services:
  nginx:
    image: nginx:1.21.6                # 镜像版本
    container_name: nginx               # 容器名,相当于docker run命令中的--name
    restart: unless-stopped             # 之前是什么状态，docker重启后，保持之前的状态（如果之前是stop，那docker重启时，也是stop状态）
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录,相当于docker run命令中的-v
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./log:/var/log/nginx
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口，相当于docker run 命令中的-p
      - "80:80"
