version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-01-02T09-40-09Z
    container_name: minio
    restart: unless-stopped
    volumes:
      - "./data:/mnt/data"
      - "./config/config.env:/etc/config.env"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_CONFIG_ENV_FILE: "/etc/config.env"
    command: server --console-address ":9090"
    ports:
      - "9001:9000"
      - "9090:9090"