version: '3.1'
services:
  zabbix-mysql8:
    image: mysql:8.0
    container_name: zabbix-mysql8
    # docker安全验证
    security_opt:
      - seccomp:unconfined
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_bin, --default-authentication-plugin=mysql_native_password]
    restart: always
    networks:
      - zabbix_net
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./mysql8/conf:/etc/mysql/conf.d
      - ./mysql8/data:/var/lib/mysql
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-alpine-latest
    container_name: zabbix-server
    restart: always
    networks:
      - zabbix_net
    depends_on:
      - zabbix-mysql8
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=zabbix-mysql8
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.0-alpine-latest
    container_name: zabbix-web
    restart: always
    networks:
      - zabbix_net
    depends_on:
      - zabbix-mysql8
    ports:
      - 80:8080
    environment:
      - DB_SERVER_HOST=zabbix-mysql8
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zabbix-agent2:
    image: zabbix/zabbix-agent2:6.0-alpine-latest
    container_name: zabbix-agent2
    restart: always
    networks:
      - zabbix_net
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  zabbix_net:
    driver: bridge