version: '3'
services:
  tengine:
    image: registry.cn-shenzhen.aliyuncs.com/linge365/tengine:2.4.0-geoip2
    container_name: tengine               # 容器名,相当于docker run命令中的--name
    restart: unless-stopped               # 之前是什么状态，docker重启后，保持之前的状态（如果之前是stop，那docker重启时，也是stop状态）
    volumes:                              # 数据卷挂载路径设置,将本机目录映射到容器目录,相当于docker run命令中的-v
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./log:/var/log/nginx
      - ./cert:/etc/nginx/cert
      #- ./geoip2:/etc/nginx/geoip2
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口，相当于docker run 命令中的-p
      - "80:80"
      - "443:443"
