version: '3.1'
services:
  gitlab-ce:
    image: gitlab/gitlab-ce:16.1.0-ce.0
    container_name: gitlab
    hostname: 'gitlab'
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
      #GITLAB_OMNIBUS_CONFIG: |
        #external_url 'http://ip'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    ports:
      - '880:80'
      - '8443:443'
      - '822:22'
