version: '3.1'
services:
  redis:
    image: redis:5
    container_name: redis
    restart: unless-stopped
    #command: redis-server --requirepass 123456 --appendonly yes
    command: redis-server /etc/redis/redis.conf
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - ./data:/data #数据文件挂载
      - ./conf/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379