version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --performance_schema=1
      --max_allowed_packet=128M
      --sql-mode=""
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql #数据文件挂载
    ports:
      - 3306:3306